---
- hosts: all
  user: root

  tasks:
   - name: Install NTP
     yum: name=chrony state=present

   - name: Make sure NTP is started up
     service: name=chronyd state=started enabled=yes

   - name: update chrony
     shell: grep -q -F 'tick.gatech.edu' /etc/chrony.conf || echo "server tick.gatech.edu" >> /etc/chrony.conf

  handlers:
   - name: restart ntp
     service: name=chronyd state=restarted
